In [3]:
import torch
import torch.nn as nn


def xavier_uniform_(tensor, gain=1.0):
    """Xavier/Glorot initialization."""
    fan_in, fan_out = tensor.size(0), tensor.size(1)
    limit = gain * torch.sqrt(torch.tensor(6.0 / (fan_in + fan_out)))
    return tensor.uniform_(-limit, limit)


# PyTorch built-in
layer = nn.Linear(512, 512)
nn.init.xavier_uniform_(layer.weight)


# Print full weight matrix
print("First layer weights:")
print(layer.weight)

# Or just inspect a small part (recommended)
print("\nFirst 5x5 block of weights:")
print(layer.weight[:5, :5])

First layer weights:
Parameter containing:
tensor([[-0.0539,  0.0499,  0.0188,  ..., -0.0307, -0.0313,  0.0528],
        [-0.0347, -0.0476,  0.0579,  ..., -0.0052, -0.0271, -0.0742],
        [-0.0160,  0.0356,  0.0059,  ...,  0.0746, -0.0054, -0.0268],
        ...,
        [-0.0134,  0.0504, -0.0216,  ...,  0.0353,  0.0372, -0.0535],
        [-0.0610,  0.0119,  0.0064,  ...,  0.0759, -0.0665,  0.0471],
        [-0.0232, -0.0765,  0.0104,  ..., -0.0074,  0.0536, -0.0245]],
       requires_grad=True)

First 5x5 block of weights:
tensor([[-0.0539,  0.0499,  0.0188,  0.0740,  0.0453],
        [-0.0347, -0.0476,  0.0579,  0.0145, -0.0493],
        [-0.0160,  0.0356,  0.0059,  0.0608, -0.0693],
        [ 0.0195,  0.0133, -0.0577,  0.0292, -0.0561],
        [ 0.0047,  0.0110, -0.0320,  0.0271,  0.0336]],
       grad_fn=<SliceBackward0>)


In [4]:
def kaiming_normal_(tensor, mode="fan_in", nonlinearity="relu"):
    """Kaiming/He initialization."""
    fan = tensor.size(1) if mode == "fan_in" else tensor.size(0)

    # Compute gain based on nonlinearity
    if nonlinearity == "relu":
        gain = torch.sqrt(torch.tensor(2.0))
    elif nonlinearity == "linear":
        gain = 1.0
    else:
        raise ValueError(f"Unsupported nonlinearity: {nonlinearity}")

    std = gain / torch.sqrt(torch.tensor(fan))
    return tensor.normal_(0, std)


# PyTorch built-in
layer = nn.Linear(512, 512)
nn.init.kaiming_normal_(layer.weight, nonlinearity="relu")

# Print full weight matrix
print("First layer weights:")
print(layer.weight)

# Or just inspect a small part (recommended)
print("\nFirst 5x5 block of weights:")
print(layer.weight[:5, :5])

First layer weights:
Parameter containing:
tensor([[ 0.0419, -0.0215,  0.0142,  ..., -0.0459,  0.0403,  0.1105],
        [-0.0346, -0.1004, -0.0494,  ...,  0.0821, -0.0277,  0.0199],
        [-0.0453,  0.0009, -0.0747,  ...,  0.0620,  0.0379, -0.0481],
        ...,
        [ 0.0217,  0.0308, -0.0789,  ...,  0.0637, -0.1007,  0.0637],
        [-0.0104, -0.0047,  0.0763,  ...,  0.0651, -0.0031, -0.0428],
        [ 0.0168, -0.0414,  0.0139,  ...,  0.0597,  0.0250, -0.0542]],
       requires_grad=True)

First 5x5 block of weights:
tensor([[ 0.0419, -0.0215,  0.0142, -0.0429,  0.0123],
        [-0.0346, -0.1004, -0.0494, -0.1723,  0.0220],
        [-0.0453,  0.0009, -0.0747, -0.0465,  0.0767],
        [ 0.1017,  0.0220,  0.0543, -0.0071, -0.0367],
        [-0.1581,  0.0453, -0.0213, -0.0140, -0.0680]],
       grad_fn=<SliceBackward0>)
