In [1]:
import numpy as np

np.random.seed(42)

# Create a batch of 3 examples with 4 features each
X = np.random.rand(3, 4)

# Define a small neural network
W1 = np.random.randn(4, 5) * 0.1  # 4 features to 5 hidden units
b1 = np.zeros(5)
W2 = np.random.randn(5, 2) * 0.1  # 5 hidden units to 2 output classes
b2 = np.zeros(2)

# Forward pass
print("Input X (batch_size=3, features=4):")
print(X)
print("\nWeight matrix W1 (features=4, hidden_units=5):")
print(W1)

Input X (batch_size=3, features=4):
[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

Weight matrix W1 (features=4, hidden_units=5):
[[-0.04694744  0.054256   -0.04634177 -0.04657298  0.02419623]
 [-0.19132802 -0.17249178 -0.05622875 -0.10128311  0.03142473]
 [-0.09080241 -0.14123037  0.14656488 -0.02257763  0.00675282]
 [-0.14247482 -0.05443827  0.01109226 -0.11509936  0.0375698 ]]


In [2]:
# First layer computation
z1 = np.dot(X, W1) + b1
print("\nz1 = X·W1 + b1 (batch_size=3, hidden_units=5):")
print(z1)


z1 = X·W1 + b1 (batch_size=3, hidden_units=5):
[[-0.35124256 -0.27963906  0.04311075 -0.19916665  0.06637291]
 [-0.16585322 -0.07379913  0.00211931 -0.12407357  0.04161144]
 [-0.30375179 -0.14522998 -0.05389532 -0.21181226  0.07337403]]


In [3]:
a1 = np.maximum(0, z1)  # ReLU activation
print("\na1 = ReLU(z1) (batch_size=3, hidden_units=5):")
print(a1)


a1 = ReLU(z1) (batch_size=3, hidden_units=5):
[[0.         0.         0.04311075 0.         0.06637291]
 [0.         0.         0.00211931 0.         0.04161144]
 [0.         0.         0.         0.         0.07337403]]


In [4]:
# Second layer computation
z2 = np.dot(a1, W2) + b2
print("\nz2 = a1·W2 + b2 (batch_size=3, output_units=2):")
print(z2)


z2 = a1·W2 + b2 (batch_size=3, output_units=2):
[[ 0.0013281  -0.01756677]
 [ 0.00086625 -0.00837863]
 [ 0.00153252 -0.01437889]]


In [5]:
# Softmax activation for output layer
exp_scores = np.exp(z2 - np.max(z2, axis=1, keepdims=True))
a2 = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
print("\na2 = softmax(z2) (batch_size=3, output_units=2):")
print(a2)
print("\nSum of probabilities for each example (should be 1):")
print(np.sum(a2, axis=1))


a2 = softmax(z2) (batch_size=3, output_units=2):
[[0.50472358 0.49527642]
 [0.5023112  0.4976888 ]
 [0.50397777 0.49602223]]

Sum of probabilities for each example (should be 1):
[1. 1. 1.]


In [6]:
# Visualizing the shapes
print("\nMatrix shapes visualization:")
shapes = [
    ("X", X.shape),
    ("W1", W1.shape),
    ("b1", b1.shape),
    ("z1", z1.shape),
    ("a1", a1.shape),
    ("W2", W2.shape),
    ("b2", b2.shape),
    ("z2", z2.shape),
    ("a2", a2.shape),
]

for name, shape in shapes:
    print(f"{name}: {shape}")


Matrix shapes visualization:
X: (3, 4)
W1: (4, 5)
b1: (5,)
z1: (3, 5)
a1: (3, 5)
W2: (5, 2)
b2: (2,)
z2: (3, 2)
a2: (3, 2)
